---
title: "Supply vs. Demand for post secondary graduates"
output: flexdashboard::flex_dashboard
runtime: shiny
resource_files:
- data/3710023501_PSE grads by CIP4 and status of students.xlsx
- data/cip_2_noc_canada.csv
- data/employment_counts_by_noc_and_post_sec.csv
- data/job_openings_occupation.xlsx
- data/Emplyment by CIP4_NOC5_Ed attained_BC_25-54.csv
---

```{r}
library(tidyverse)
library(here)
library(vroom)
library(janitor)
library(readxl)
library(conflicted)
library(qdapRegex)
library(knitr)
library(plotly)
conflicts_prefer(dplyr::filter)
```


```{r, cache=TRUE}
#constants-------------------
number_lumps <- 6
letters <- "[:alpha:]"
min_year <- 2024 #will need to increment this once we get the lmo 2024 data
prop_international <- 0 #the proportion of international students that stay
imbalance_greater <- 200 #only plot imbalances greater than this
#functions
col_plot <- function(broad, title, cutoff){
  to_plot|>
    filter(broad_noc==broad,
           abs(`Excess demand`)>cutoff)|>
    ggplot(aes(`Excess demand`,
               fct_reorder(NOC, `Excess demand`),
               text=paste(
                 "NOC: ",
                 NOC,
                 "\n Excess Demand: ",
                 `Excess demand`
               )
    )
    )+
    geom_col()+
    scale_x_continuous(labels=scales::comma)+
    coord_cartesian(xlim = c(-5000,10000))+
    labs(y=NULL,
         title=title)
}

fix_data <- function(vctr){
  vctr|>
    str_remove_all(",")|>
    as.numeric()
}
get_cagr <- function(tbbl){
  start <- tbbl$graduates[tbbl$year==min(tbbl$year)]
  end <-  tbbl$graduates[tbbl$year==max(tbbl$year)]
  time <-  max(tbbl$year)-min(tbbl$year)
  case_when(start==0 ~ 2, # CAGR =100% rather than Inf
            end==0 ~ .5, # CAGR = -50% rather than -100%
            TRUE ~ (end/start)^(1/(time)) #if neither start or end =0, actual cagr
  )
}
multiply_prop <- function(tbbl, grads){
  tbbl|>
    mutate(value=value*grads)
}
make_forecast <- function(tbbl, mean_year, mean_grads, cagr){
  tbbl|>
    mutate(forecast_grads=mean_grads*cagr^(year-mean_year))
}
my_dt <- function(tbbl) {
  DT::datatable(tbbl,
                filter = 'top',
                extensions = "Buttons",
                rownames = FALSE,
                options = list(
                  columnDefs = list(list(className = "dt-center", targets = "_all")),
                  paging = TRUE,
                  scrollX = TRUE,
                  scrollY = TRUE,
                  searching = TRUE,
                  ordering = TRUE,
                  dom = "Btip",
                  buttons = list(
                    list(extend = "csv", filename = "employment_counts_by_cip_teer"),
                    list(extend = "excel", filename = "employment_counts_by_cip_teer")
                  ),
                  pageLength = 11
                )
  )
}
# get and process the data
cip_noc_long <- vroom(here("data","Emplyment by CIP4_NOC5_Ed attained_BC_25-54.csv"))|>
  filter(`High. Cert. (13)`=="Post-secondary certificate, diploma or degree")|>
  select(-`High. Cert. (13)`)|>
  rename(NOC=`NOC (821)`)|>
  filter(str_detect(NOC, "\\d\\d\\d\\d\\d"))|> #only keep 5 digit NOCs
  pivot_longer(cols=-NOC, names_to = "field_of_study", values_to = "value")|>
  filter(str_detect(field_of_study, "\\d\\d\\.\\d\\d"))|> #only keep 4 digit CIPs (with a dot in the middle)
  filter(value>0)|>
  mutate(CIP=str_sub(field_of_study, 1, 5),
         field_of_study=str_sub(field_of_study, 7))

by_teer <- cip_noc_long|>
  mutate(TEER=if_else(str_sub(NOC, 2,2) %in% 4:5, "TEER_45", "TEER_0123"))|>
  group_by(field_of_study, TEER)|>
  summarize(value=sum(value, na.rm = TRUE))|>
  pivot_wider(names_from = TEER, values_from = value)|>
  mutate(across(contains("TEER"), ~ if_else(is.na(.x), 0, .x)),
         prop_45=TEER_45/(TEER_45+TEER_0123))

# cip_noc_long <- vroom::vroom(here("data","cip_2_noc_canada.csv"), skip = 13)[-1,]
# colnames(cip_noc_long)[1] <- "field_of_study"
# cip_noc_long <- cip_noc_long|>
#   remove_empty("cols")|>
#   pivot_longer(cols=-field_of_study, names_to = "NOC", values_to = "value")|>
#   mutate(value=as.numeric(str_remove_all(value,",")),
#          CIP=str_sub(field_of_study, 1, 5),
#          field_of_study=str_sub(field_of_study, 7))|>
#   filter(value>0)

job_openings_raw <- readxl::read_excel(here("data","job_openings_occupation.xlsx"), skip = 3)|>
  remove_constant()|>
  filter(NOC!="#T",
         Variable=="Job Openings",
         `Geographic Area`=="British Columbia"
  )|>
  select(-Variable, -`Geographic Area`)|>
  mutate(NOC=str_remove(NOC,"#"))|>
  unite("NOC", NOC, Description, sep=" ")|>
  pivot_longer(cols = starts_with("2"), names_to = "year", values_to = "job_openings")|>
  mutate(year=as.integer(year))|>
  filter(year>=min_year)

#Note that this is CANADA data, not BC
counts_by_noc_post_sec <- read_csv(here("data",
                                        "employment_counts_by_noc_and_post_sec.csv"),
                                   skip = 15,
                                   n_max = 512, col_names = c("NOC", "total", "post_secondary")
)|>
  mutate(teer=str_sub(NOC, 2,2),
         prop_post_sec=post_secondary/total)

noc123 <- counts_by_noc_post_sec|>
  filter(str_sub(NOC,2,2) %in% 1:3)|>
  arrange(NOC)|>
  pull(NOC)

job_openings <- inner_join(job_openings_raw, counts_by_noc_post_sec)|>
  na.omit()|>
  mutate(job_openings=job_openings*prop_post_sec)|> #proportion of job openings requiring post secondary
  group_by(NOC)|>
  summarize(job_openings=sum(job_openings))

empty_tbbl <- tibble(year=min(job_openings_raw$year):max(job_openings_raw$year)) #for storing the new entrant forecast

new_grads_raw <- read_excel(here("data", "3710023501_PSE grads by CIP4 and status of students.xlsx"))|>
  clean_names()|>
  select(year=ref_date, field_of_study, status_of_student_in_canada, graduates=value)|>
  filter(status_of_student_in_canada %in% c("Canadian students", "International students"))|>
  mutate(CIP=ex_between(field_of_study,"[","]"),
         CIP=str_remove_all(CIP, letters),
         field_of_study=word(field_of_study, sep="\\["),
         field_of_study=trimws(field_of_study)
  )|>
  pivot_wider(names_from = status_of_student_in_canada, values_from = graduates)|>
  clean_names()|>
  mutate(canadian_students=if_else(is.na(canadian_students),0, canadian_students),
         international_students=if_else(is.na(international_students),0, international_students),
         graduates=canadian_students+prop_international*international_students)|>
  select(-contains("students"))|>
  group_by(field_of_study, cip)|>
  slice_max(year, n=5)

total_by_year <- new_grads_raw|>
  group_by(year)|>
  summarize(graduates=sum(graduates))

mean_cagr <-(total_by_year$graduates[total_by_year$year==max(total_by_year$year)]/
               total_by_year$graduates[total_by_year$year==max(total_by_year$year)-4])^.25

new_grads <- new_grads_raw|>
  mutate(mean_year=mean(year),
         mean_grads=mean(graduates))|>
  group_by(field_of_study, cip, mean_year, mean_grads)|>
  nest()|>
  ungroup()|>
  filter(mean_grads>10, #filter out the worst of the data
         mean_year>2017,
         mean_year<2020)|>
  mutate(raw_cagr=map_dbl(data, get_cagr),
         mean_cagr=mean_cagr,
         cagr=.1*raw_cagr+.9*mean_cagr,
         new_entrants=list(empty_tbbl),
         new_entrants=pmap(list(new_entrants, mean_year, mean_grads, cagr), make_forecast)
  )|>
  select(field_of_study, cip, new_entrants)|>
  unnest(new_entrants)

cip_prop <- cip_noc_long|>
  rename(cip=CIP)|>
  group_by(field_of_study, cip)|>
  mutate(value=value/sum(value))|>
  nest()

new_entrants <- inner_join(cip_prop, new_grads, by="cip")|>
  mutate(data=map2(data, forecast_grads, multiply_prop))|>
  ungroup()|>
  select(field_of_study=field_of_study.x, data, year)|>
  unnest(data)

lumped_cip_noc <- cip_noc_long|>
  group_by(field_of_study)|>
  mutate(value=value/sum(value),
         NOC=fct_lump_n(NOC, n=number_lumps, w=value))|>
  group_by(field_of_study, NOC)|>
  summarize(value=sum(value)) #adds up all the "Other" proportions
```

Supply vs Demand
==============================================================


Inputs {.sidebar data-width=400}
-------------------------------------

*  This app allows one to compare the projected supply of new graduates with demand for new graduates by occupation.
*  We start by forecasting new graduates (by field of study) over the horizon of the LMO.
*  The forecast of new graduates is allocated to NOCs on the basis of the historic relationship between fields of study and occupation.
*  Job openings by occupation are deflated by the historic proportion of workers in an occupation that have post secondary education.
*  In the plots to the right, the supply of new graduates to an occupation is broken down by their field of study (the wide coloured bars)
*  The demand for new graduates is the deflated LMO job openings (the narrow grey bar)
*  If the narrow grey bar is longer than the coloured bar there is excess demand.
*  If the narrow grey bar is shorter than the coloured bar there is excess supply.
*  To see the values hover over the plot.

```{r}
# shiny inputs defined here 
selectInput(
  "nocs",
  "Choose a few NOCs you wish to compare",
  noc123,
  c("41221 Elementary school and kindergarten teachers",
    "41220 Secondary school teachers"),
  multiple = TRUE
)
```
 

```{r}
# reactive elements here

job_openings_reactive <- reactive({
  job_openings_raw|>
     filter(NOC %in% input$nocs)
})

prop_jo_reactive <- reactive({
  inner_join(job_openings_reactive(), counts_by_noc_post_sec)|>
  na.omit()|>
  mutate(job_openings=job_openings*prop_post_sec)|> #proportion of job openings requiring post secondary
  group_by(NOC)|>
  summarize(job_openings=sum(job_openings))
})

new_entrants_reactive <- reactive({
  new_entrants|>
    filter(NOC %in% input$nocs)|>
    group_by(field_of_study, NOC)|>
    summarize(value=sum(value))
})

lumped_reactive <- reactive({ 
  new_entrants_reactive()|>
  group_by(NOC)|>
  mutate(field_of_study=fct_lump_n(field_of_study, n=number_lumps, w=value))|>
  group_by(field_of_study, NOC)|>
  summarize(value=sum(value))|>
  group_by(NOC)|>
  mutate(total_entrants=sum(value))
})

```
 
 
Column
-------------------------------------
    
### 
    
```{r}
renderPlotly({
  plt <- ggplot()+
  geom_bar(data=lumped_reactive(), mapping=aes(value,
                                    NOC,
                                    fill=fct_relevel(fct_reorder(field_of_study, value),"Other", after=0),
                                     text=paste0(
                                       "Field of Study: ",
                                       field_of_study,
                                       "\n Entrants: ",
                                       scales::comma(value, accuracy = 1),
                                       "\n Total Entrants: ",
                                       scales::comma(total_entrants, accuracy = 1)
                                     )
  ), stat="identity", alpha=.75)+
  geom_bar(data=prop_jo_reactive(), mapping=aes(job_openings,
                                          NOC,
                                          text=paste0(
                                            "The number of job openings requiring some post secondary education is ",
                                            scales::comma(job_openings, accuracy = 1))), stat="identity", width = .1, alpha=.9)+
  scale_x_continuous(labels = scales::comma)+
  scale_fill_viridis_d()+
  labs(title="Supply (by field of study) vs. Demand for post secondary graduates",
       fill="Field of Study",
       x=NULL,
       y=NULL)+
  theme_minimal()

ggplotly(plt, tooltip = "text")
})
```
  
Destination Occupations by Field of Study
=================================================

Inputs {.sidebar data-width=400}
-------------------------------------

*  One might also be interested in the opposite perspective:  For a given field of study, what is the breakdown of destination occupations?

```{r}
# shiny inputs defined here 
selectInput(
  "cips",
  "Choose a few CIPs you wish to compare",
  unique(lumped_cip_noc$field_of_study),
  c("Teacher education and professional development, specific subject areas",
    "Education, general"),     
  multiple = TRUE
)
```
 

```{r}
# reactive elements here
lumped_cip_noc_reactive <- reactive({
  lumped_cip_noc|>
   filter(field_of_study %in% input$cips)
})
```
 
 
Column
-------------------------------------
    
### 

```{r}
renderPlotly({
 plt <- ggplot()+
  geom_bar(data=lumped_cip_noc_reactive(), mapping=aes(value,
                                    field_of_study,
                                    fill=fct_reorder(NOC, value),
                                    text=paste0(
                                      "NOC: ",
                                      NOC,
                                      "\n Proportion: ",
                                      scales::percent(value, accuracy = 1)
                                    )
  ), stat="identity", position="dodge", alpha=.75)+
  scale_x_continuous(labels = scales::percent)+
  scale_fill_viridis_d()+
  labs(title="Destination occupations for fields of study",
       fill="NOC",
       x=NULL,
       y=NULL)+
  theme_minimal()

ggplotly(plt, tooltip = "text") 
})
```

Employment counts by CIP and TEER
=================================================

Inputs {.sidebar data-width=400}
-------------------------------------

*  One might also be interested in the TEER category of the destination occupations associated with the fields of study.


Column
-----------------------------------------------

###

```{r}
plt <- ggplot(by_teer, aes(TEER_0123, 
                                TEER_45, 
                                colour=prop_45, 
                                text=paste0("For those who studied ",
                                            field_of_study,
                                            ",\n",
                                            TEER_0123,
                                            " are employed in TEER 0, 1, 2, or 3 occupations, \n whereas ",
                                            TEER_45,
                                            " (",
                                            scales::percent(prop_45, accuracy = .1),
                                            ") are employed in TEER 4 or 5 occupations"
                                            )
                                )
              )+
 # geom_abline(slope = 1, intercept = 0, colour="grey")+
  geom_jitter(width=.05, height=.05, alpha=.75)+
  scale_x_continuous(trans=scales::pseudo_log_trans(base = 10), labels = scales::comma)+
  scale_y_continuous(trans=scales::pseudo_log_trans(base = 10), labels = scales::comma)+
  scale_colour_viridis_c(labels=scales::percent)+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1))+
  labs(title="Employment counts by Field of Study and TEER",
       x="Number employed in TEER 0,1,2 or 3",
       y="Number employedd in TEER 4 or 5",
       colour="In TEER 4 or 5")


ggplotly(plt, tooltip = "text")
```

The by-TEER data (previous plot)
==========================================

```{r}
my_dt(by_teer)
```

    
